services:
  socks-proxy:
    container_name: tor-socks-proxy
    image: ghcr.io/leicraft/tor-socks-proxy
    ports:
      - "0.0.0.0:9150:9150/tcp"
      - "[::]:9150:9150/tcp"
    restart: unless-stopped

networks:
  default:
    driver: bridge